# Generated by Django 3.2.7 on 2021-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('address', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
